const fs=require('fs');
// игра берётся из собранного index.html (сначала: python3 tools/build.py)
const html=fs.readFileSync(require('path').resolve(__dirname,'../../index.html'),'utf8');
let code=html.slice(html.indexOf('<script>')+8,html.lastIndexOf('</script>'));
code=code.replace('function damagePlayer(n){',"function damagePlayer(n){if(globalThis.DMG){const st=new Error().stack.split('\\n')[2]||'';const m=st.match(/at (\\S+)/);const k=(m?m[1]:'?')+(DG?'·склеп':'')+(phase().night?'·ночь':'');DMG[k]=(DMG[k]||0)+n}");
code=code.replace('function toast(msg,kind,key){',"function toast(msg,kind,key){(globalThis.TOASTS=globalThis.TOASTS||[]).push(String(msg));").replace('function addFloat(x,y,text,color){',"function addFloat(x,y,text,color){(globalThis.TOASTS=globalThis.TOASTS||[]).push(String(text));");
code=code.replace(/\}\)\(\);\s*$/,"globalThis.G_={get S(){return S},set S(v){S=v},WAR,REZ,heroArmor,trees2:()=>trees,portalPos,allCleared,bagCap,inCamp,merchantHere,hqMax,heroStats,get menuOpen2(){return menuOpen},drinkPotion,useRelic,ownedRelics,RELIC2,openMenu,MENUS,get menuKind(){return menuKind},get menuOpen(){return menuOpen},openMenuHere,updRelicBar,openCryptGate,PERKS,perkDesc,brLabel,MASTERY,RELICS,RELIC2,PETS_:typeof PETS!='undefined'?PETS:null,SETAB,UNIQUES,MERCH,CRYPT_PH,LORE_T,LORE_B,heroStats,TABS,secName,get floats(){return floats},TUT,CFG,tutOn,zoneAt,tutClaim,get tutTarget(){return tutTarget},zoneCleared,fillQuests,openTut,renderTut,closeTut,P,get DG(){return DG},zombies:()=>zombies,drops:()=>drops,pois:()=>pois,crypts:()=>crypts,lairs:()=>lairs,rocks:()=>rocks,refugees:()=>refugees,mounds:()=>mounds,applyState,doAct,rowsFor,enterCrypt,openDunChest,leaveCrypt,makeItem,gear,heroHit,hitZombie,killZombie,makeBoss,summonFinal,spawnCaravan,newGame,specialTarget,findTarget,startNight,endNight,showVictory,showRelics,maxHp,speedOf,buildWorld,renderMenu,toggleMenu,get tab(){return tab},set tab(v){tab=v},render,mast,combo,logRows,applyOffline,hitEnemy,chop,towerHit,trees:()=>trees,parts:()=>parts,get slowT(){return slowT},brPts,bestiary,ACH,COMBOS,els_dawn:()=>document.getElementById('dawnList'),useRelic,RX,phoenixSave,ownedRelics,showRelics,get relicOffer(){return relicOffer},doAction,update,keys,WG,isSea,sideAt,zoneAt,toLand,trees:()=>trees,patches:()=>patches,get W(){return W_SIZE},get CX(){return CX},migrate,cryptDiff,SETS,setCount,makeSetItem,gear,updateDungeon,ownedSet,useAbility,secAttack,makeZombie,perkAvail,perkName,CLASSES,damagePlayer,rollPerks,get tracers(){return tracers},DEF,updateDefense,defAct,onIce,zSlow,DFX,phase,trapPos,ballPos,bowlPos,guardDmg,get pets(){return typeof PETS!='undefined'?PETS:null},drawPlayer,drawHeroBody,drawZombie:typeof drawZombie!='undefined'?drawZombie:null,hammerTargets:typeof hammerTargets!='undefined'?hammerTargets:null,useSetAbility:typeof useSetAbility!='undefined'?useSetAbility:null,get SX(){return typeof SX!='undefined'?SX:null},fullSet:typeof fullSet!='undefined'?fullSet:null,newGameF:typeof newGame!='undefined'?newGame:null,specialTarget,ngMul,costMul,incMul,zCnt,disc,ARENA:()=>ARENA_R,zoneCleared};})();");
const noop=()=>{};
const ctxProxy=new Proxy({},{get:(t,k)=>k==='createRadialGradient'||k==='createLinearGradient'?()=>({addColorStop:noop}):k==='measureText'?()=>({width:10}):k==='fillText'||k==='strokeText'?(t)=>{(globalThis.CTXT=globalThis.CTXT||new Set()).add(String(t))}:(k in t?t[k]:noop),set:(t,k,v)=>{t[k]=v;return true}});
const els={};
function el(id){if(els[id])return els[id];const e={id,style:{setProperty(){}},hidden:['perks','over','win','menu','dawn','tut'].includes(id),textContent:'',innerHTML:'',value:'',dataset:{},classList:{add:noop,remove:noop,toggle:noop,contains:()=>false},addEventListener:noop,setAttribute:noop,setPointerCapture:noop,firstChild:{style:{},remove(){}},children:[],appendChild(c){this.children.push(c);const s=this;this.firstChild={style:{},remove(){s.children.shift()}}},append:noop,select:noop,getContext:()=>ctxProxy,closest:()=>null,remove:noop,querySelector:()=>null,querySelectorAll:()=>[]};if(id==='clsPick')Object.defineProperty(e,'hidden',{get(){return true},set(){}});els[id]=e;return e}
const listeners={};
global.window=global;global.Image=function(){this.complete=true;this.naturalWidth=32};global.innerWidth=1280;global.innerHeight=800;global.devicePixelRatio=1;global.matchMedia=()=>({matches:false});
global.addEventListener=(t,f)=>{(listeners[t]=listeners[t]||[]).push(f)};
global.document={documentElement:{classList:{add(){},contains(){return false}}},getElementById:el,createElement:()=>el('x'+Math.random()),addEventListener:noop,hidden:false};
global.store={};global.localStorage={getItem:k=>store[k]??null,setItem:(k,v)=>{store[k]=String(v)}};
let raf=null;global.requestAnimationFrame=f=>{raf=f};global.navigator={};
global.setTimeout=(f,ms)=>{global.__timers.push(f);return 1};global.__timers=[];global.clearTimeout=noop;
global.performance={now:()=>T};let T=0;
global.boot=()=>{eval(code);};
global.tick=ms=>{T+=ms};
global.frames=n=>{for(let i=0;i<n;i++){if(globalThis.G_&&G_.S&&!G_.S.cls&&!globalThis.NO_CLS)G_.S.cls='archer';T+=33;const f=raf;raf=null;f(T)}};
global.key=(code,down)=>{(listeners[down?'keydown':'keyup']||[]).forEach(f=>f({code,target:{},preventDefault:noop}))};
global.flushTimers=()=>{const t=global.__timers;global.__timers=[];t.forEach(f=>f())};
global.els=els;
